### PR TITLE
improvement: replace custom classNames utility

### PR DESCRIPTION
**Pull request by mealCode**
## Work Done
Replace custom classNames utility with a  classnames npm library for better merging classnames options

### CODE REVIEW

**Review by siegblink — CHANGES_REQUESTED** [review]
@mealCode It appears the `classnames` npm package doesn't work well after running the `build` script.

Perhaps consider finding a compatible version that doesn't throw an error during the build process.

After that, let's revisit this.

**Comment by mealCode** [comment]
> @mealCode It appears the `classnames` npm package doesn't work well after running the `build` script.
> 
> Perhaps consider finding a compatible version that doesn't throw an error during the build process.
> 
> After that, let's revisit this.

@siegblink 
I was able to build the project using the `yarn build` command though i had to do `yarn install` first, it seems that the `classnames` package isn't available in the `yarn.lock` causing the build issue. I think we need a new script `"build:production": "yarn install && yarn build"` to install package and build project at the same time.

image

**Comment by siegblink** [comment]
> > @mealCode It appears the `classnames` npm package doesn't work well after running the `build` script.
> > Perhaps consider finding a compatible version that doesn't throw an error during the build process.
> > After that, let's revisit this.
> 
> @siegblink I was able to build the project using the `yarn build` command though i had to do `yarn install` first, it seems that the `classnames` package isn't available in the `yarn.lock` causing the build issue. I think we need a new script `"build:production": "yarn install && yarn build"` to install package and build project at the same time.
> 
> image

@mealCode I see that you are using `yarn` on your side.

For the sake of simplicity, is there a way you can use `npm` as package manager and package installer for now in this project?

As much as possible, I try to avoid keeping 2 lock files, namely keeping both `package-lock.json` and `yarn.lock` files.

Otherwise, it will end up introducing complexity or confusion which I don't really want to happen.

**Comment by mealCode** [comment]
> > > @mealCode It appears the `classnames` npm package doesn't work well after running the `build` script.
> > > Perhaps consider finding a compatible version that doesn't throw an error during the build process.
> > > After that, let's revisit this.
> > 
> > 
> > @siegblink I was able to build the project using the `yarn build` command though i had to do `yarn install` first, it seems that the `classnames` package isn't available in the `yarn.lock` causing the build issue. I think we need a new script `"build:production": "yarn install && yarn build"` to install package and build project at the same time.
> > image
> 
> @mealCode I see that you are using `yarn` on your side.
> 
> For the sake of simplicity, is there a way you can use `npm` as package manager and package installer for now in this project?
> 
> As much as possible, I try to avoid keeping 2 lock files, namely keeping both `package-lock.json` and `yarn.lock` files.
> 
> Otherwise, it will end up introducing complexity or confusion which I don't really want to happen.

Hi @siegblink , my bad I didn't notice I used yarn as I haven't used npm for a while in my machine. Though, using npm works fine also (after i revert yarn):

image

**Comment by mealCode** [comment]
> @mealCode It appears the `classnames` npm package doesn't work well after running the `build` script.
> 
> Perhaps consider finding a compatible version that doesn't throw an error during the build process.
> 
> After that, let's revisit this.

@siegblink - can you elaborate what build issue you had encounter? Thanks

@mealCode Here's the most recent build error message that's provided on the Vercel project page:

image

On the other hand, I reproduced what you did on your local dev environment.

So, I was able to run build script locally and did not encounter any errors. Looks like this is Vercel-specific issue.

That aside, I just noticed a conflict on the `app/desktop-sidebar.tsx` file today.

When you have the time, can you please resolve this tiny conflict on the affected file?

**Comment by siegblink** [comment]
> > @mealCode It appears the `classnames` npm package doesn't work well after running the `build` script.
> > Perhaps consider finding a compatible version that doesn't throw an error during the build process.
> > After that, let's revisit this.
> 
> @siegblink - can you elaborate what build issue you had encounter? Thanks
> 
> @mealCode Here's the most recent build error message that's provided on the Vercel project page:
> 
> image
> 
> On the other hand, I reproduced what you did on your local dev environment.
> 
> So, I was able to run build script locally and did not encounter any errors. Looks like this is Vercel-specific issue.
> 
> That aside, I just noticed a conflict on the `app/desktop-sidebar.tsx` file today.
> 
> When you have the time, can you please resolve this tiny conflict on the affected file?

I am closing this PR due to inactivity.

**Comment by mealCode** [comment]
> > > @mealCode It appears the `classnames` npm package doesn't work well after running the `build` script.
> > > Perhaps consider finding a compatible version that doesn't throw an error during the build process.
> > > After that, let's revisit this.
> > 
> > 
> > @siegblink - can you elaborate what build issue you had encounter? Thanks
> > @mealCode Here's the most recent build error message that's provided on the Vercel project page:
> > image
> > On the other hand, I reproduced what you did on your local dev environment.
> > So, I was able to run build script locally and did not encounter any errors. Looks like this is Vercel-specific issue.
> > That aside, I just noticed a conflict on the `app/desktop-sidebar.tsx` file today.
> > When you have the time, can you please resolve this tiny conflict on the affected file?
> 
> I am closing this PR due to inactivity.

Hi @siegblink - i don't get notified when you edit my message rather than quote replied to it.

**Comment by siegblink** [comment]
> > > > @mealCode It appears the `classnames` npm package doesn't work well after running the `build` script.
> > > > Perhaps consider finding a compatible version that doesn't throw an error during the build process.
> > > > After that, let's revisit this.
> > > 
> > > 
> > > @siegblink - can you elaborate what build issue you had encounter? Thanks
> > > @mealCode Here's the most recent build error message that's provided on the Vercel project page:
> > > image
> > > On the other hand, I reproduced what you did on your local dev environment.
> > > So, I was able to run build script locally and did not encounter any errors. Looks like this is Vercel-specific issue.
> > > That aside, I just noticed a conflict on the `app/desktop-sidebar.tsx` file today.
> > > When you have the time, can you please resolve this tiny conflict on the affected file?
> > 
> > 
> > I am closing this PR due to inactivity.
> 
> Hi @siegblink - i don't get notified when you edit my message rather than quote replied to it.

@mealCode It's alright. You're good. And everything is okay.

For now, I believe it's best to leave it this way.

I truly appreciate the contributions you have made.

I will investigate and document this issue during my free time.

And in the coming days, I will upgrade to Next.js 14 and improve this project further by addressing the feature requests I have made.

**Comment by mealCode** [comment]
> > > > > @mealCode It appears the `classnames` npm package doesn't work well after running the `build` script.
> > > > > Perhaps consider finding a compatible version that doesn't throw an error during the build process.
> > > > > After that, let's revisit this.
> > > > 
> > > > 
> > > > @siegblink - can you elaborate what build issue you had encounter? Thanks
> > > > @mealCode Here's the most recent build error message that's provided on the Vercel project page:
> > > > image
> > > > On the other hand, I reproduced what you did on your local dev environment.
> > > > So, I was able to run build script locally and did not encounter any errors. Looks like this is Vercel-specific issue.
> > > > That aside, I just noticed a conflict on the `app/desktop-sidebar.tsx` file today.
> > > > When you have the time, can you please resolve this tiny conflict on the affected file?
> > > 
> > > 
> > > I am closing this PR due to inactivity.
> > 
> > 
> > Hi @siegblink - i don't get notified when you edit my message rather than quote replied to it.
> 
> @mealCode It's alright. You're good. And everything is okay.
> 
> For now, I believe it's best to leave it this way.
> 
> I truly appreciate the contributions you have made.
> 
> I will investigate and document this issue during my free time.
> 
> And in the coming days, I will upgrade to Next.js 14 and improve this project further by addressing the feature requests I have made.

Awesome thanks @siegblink

**Pull request closed without merging**
